
name = "cryptocurrencies"
version = "0.1.0"
description = "My awesome plugin description"
author = "Karmatoast40340"
license = "UNLICENSED"
repository = ""
homepage = ""
type = "anyquery"
minimumAnyqueryVersion = "0.0.1"

tables = ["notion"]

# The user configuration schema
[[userConfig]]
name = "my_token"
description = "A description of why this token is needed"
type = "string"
required = true # If the user must provide a value

[[file]]
platform = "linux/amd64"
directory = "dist/anyquery_linux_amd64_v1"
executablePath = "notion"

[[file]]
platform = "linux/arm64"
directory = "dist/anyquery_linux_arm64"
executablePath = "notion"

[[file]]
platform = "darwin/amd64"
directory = "dist/anyquery_darwin_amd64_v1"
executablePath = "notion"

[[file]]
platform = "darwin/arm64"
directory = "dist/anyquery_darwin_arm64"
executablePath = "notion"

[[file]]
platform = "windows/amd64"
directory = "dist/anyquery_windows_amd64_v1"
executablePath = "notion.exe"

[[file]]
platform = "windows/arm64"
directory = "dist/anyquery_windows_arm64"
executablePath = "notion.exe"
